[project]
name = "dates_calc"
description = "A date calculation library"
version = "0.10.0"
dependencies = [
  "typing",
  "mypy",
  "types-termcolor",
  "typer[all]",
  "typing-extensions"
]

[project.optional-dependencies]
test = [
  "unittest",
  "csv"
]

[project.urls]
"Homepage" = "https://github.com/CatalaLang/dates-calc"
"Bug Tracker" = "https://github.com/CatalaLang/dates-calc/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/catala"]
