/* This file has been generated by the Catala compiler, do not edit! */

#ifndef __PRORATA_EXTERNAL_H__
#define __PRORATA_EXTERNAL_H__


const CATALA_ARRAY(CATALA_MONEY) ProrataExternal__prorata
    (CATALA_MONEY amount, const CATALA_ARRAY(CATALA_MONEY) weights);

const CATALA_ARRAY(CATALA_MONEY) ProrataExternal__prorata2
    (CATALA_MONEY amount, const CATALA_ARRAY(CATALA_MONEY) weights);

#endif /* __PRORATA_EXTERNAL_H__ */
