# This file has been generated by the Catala compiler, do not edit!

from catala.runtime import *
from typing import Any, List, Callable, Tuple
from enum import Enum


def prorata(amount:Money, weights:List[Money]):
    return []

def prorata2(amount:Money, weights:List[Money]):
    return []
