/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;

public class Prorata_external {
    
    public static class Globals {
        
        public static final CatalaFunction<CatalaTuple,CatalaArray<CatalaMoney>> prorata =
            tup_arg_5 -> {
            CatalaMoney amount = ((CatalaMoney)tup_arg_5.get(0));
            CatalaArray<CatalaMoney> weights =
                ((CatalaArray<CatalaMoney>)tup_arg_5.get(1));
            return new CatalaArray<>(); };
        
        public static final CatalaFunction<CatalaTuple,CatalaArray<CatalaMoney>> prorata2 =
            tup_arg_6 -> {
            CatalaMoney amount = ((CatalaMoney)tup_arg_6.get(0));
            CatalaArray<CatalaMoney> weights =
                ((CatalaArray<CatalaMoney>)tup_arg_6.get(1));
            return new CatalaArray<>(); };
    }
    
    // Automatic Catala tests
    public static void main(String[] args) {
        
    }
    
}
