(* This file is part of the Catala build system, a specification language for
   tax and social benefits computation rules. Copyright (C) 2020-2025 Inria,
   contributors: Denis Merigoux <denis.merigoux@inria.fr>, Emile Rolley
   <emile.rolley@tuta.io>, Louis Gesbert <louis.gesbert@inria.fr>

   Licensed under the Apache License, Version 2.0 (the "License"); you may not
   use this file except in compliance with the License. You may obtain a copy of
   the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
   License for the specific language governing permissions and limitations under
   the License. *)

open Clerk_utils

val backend_name : string
val catala_flags_ocaml : Var.t
val ocamlc_exe : Var.t
val ocamlopt_exe : Var.t
val ocaml_flags : Var.t
val ocaml_include_flag : Var.t

val runtime_ocaml :
  string ->
  ocaml_src:string ->
  dates_base:string ->
  ocaml_base:string ->
  Ninja_utils.def list

module Flags : sig
  val ocaml_include_and_lib : (string list * string list) lazy_t
  val ocaml_link : string list lazy_t
  val ocaml_include : string list lazy_t

  val default :
    variables:(string * string list) list ->
    autotest:bool ->
    use_default_flags:bool ->
    test_flags:string list ->
    include_dirs:string list ->
    (Var.t * string list) list
end

val linking_command :
  build_dir:string ->
  var_bindings:(Var.t * string list) list ->
  ('a -> Scan.item list) ->
  'a ->
  string ->
  string list
(** [linking_command] is a that returns a list of parameter that represents a
    command to link all the files that were generated by the Ninja file. This
    command is needed by the Clerk_driver modules and not the clerk_rules
    modules that's why it doesn't appear in the Backend common interface. *)

val run_artifact : test:bool -> ?scope:string -> string -> int
(** [run_artifact] runs the command generated by [linking_command]. This command
    is needed by the Clerk_driver modules and not the clerk_rules modules that's
    why it doesn't appear in the Backend common interface. *)

module Backend : Backend.S
