(rule
 (mode promote)
 (action
  (with-stdout-to french.ml
   (pipe-stdout
    (run %{exe:../gen/ocaml.exe} %{dep:../french.json})
    (run ocamlformat - --impl)))))

(rule
 (mode promote)
 (action
  (with-stdout-to english.ml
   (pipe-stdout
    (run %{exe:../gen/ocaml.exe} %{dep:../english.json})
    (run ocamlformat - --impl)))))

(library
 (name languages)
 (public_name catala.languages)
 (libraries catala.surface atd_language)
 (flags (:standard -linkall))
 (modules langs french english sig)
)
