(* This file was auto-generated based on "parser.messages". *)

(* Please note that the function [message] can raise [Not_found]. *)

let message s =
  match s with
  | 0 -> "expected a law heading, a law article, some text of the declaration of a master file\n"
  | 1 ->
      "expected an inclusion of a Catala file, since this file is a master file which can only \
       contain inclusions of other Catala files\n"
  | 3 -> "expected some text or includes only\n"
  | 7 ->
      "expected another inclusion of a Catala file, since this file is a master file which can \
       only contain inclusions of other Catala files\n"
  | 8 -> "expected some text, another heading or a law article\n"
  | 375 -> "expected a heading, an article title or some text\n"
  | 360 -> "expected an article title, another heading or some text\n"
  | 365 -> "expected a code block, a metadata block, more law text or a heading\n"
  | 371 -> "expected a code block, a metadata block, more law text or a heading\n"
  | 366 -> "expected a declaration or a scope use\n"
  | 22 -> "expected the name of the scope you want to use\n"
  | 24 -> "expected a scope use precondition or a colon\n"
  | 25 -> "expected an expression which will act as the condition\n"
  | 26 -> "expected the first component of the date literal\n"
  | 28 -> "expected a \"/\"\n"
  | 29 -> "expected the second component of the date literal\n"
  | 30 -> "expected a \"/\"\n"
  | 31 -> "expected the third component of the date literal\n"
  | 32 -> "expected a delimiter to finish the date literal\n"
  | 70 -> "expected an operator to compose the expression on the left with\n"
  | 113 -> "expected an enum constructor to test if the expression on the left\n"
  | 112 -> "expected an operator to compose the expression on the left with\n"
  | 145 -> "expected an expression on the right side of the sum or minus operator\n"
  | 187 -> "expected an expression on the right side of the logical operator\n"
  | 121 -> "expected an expression for the argument of this function call\n"
  | 179 -> "expected an expression on the right side of the comparison operator\n"
  | 154 -> "expected an expression on the right side of the multiplication or division operator\n"
  | 147 -> "expected an operator to compose the expression on the left\n"
  | 132 -> "expected an expression standing for the set you want to test for membership\n"
  | 71 -> "expected an identifier standing for a struct field or a subscope name\n"
  | 242 -> "expected a colon after the scope use precondition\n"
  | 76 -> "expected a constructor, to get the payload of this enum case\n"
  | 35 -> "expected the \"for\" keyword to spell the aggregation\n"
  | 181 -> "expected an expression to take the negation of\n"
  | 110 -> "expected an expression to take the opposite of\n"
  | 51 -> "expected the type of the elements compared for the minimum\n"
  | 52 -> "expected the \"initial\" keyword to introduce the minimum initial expression\n"
  | 53 -> "expected the minimum initial expression\n"
  | 55 -> "expected the type of the elements compared for the maximum\n"
  | 56 -> "expected the \"initial\" keyword to introduce the maximum initial expression\n"
  | 57 -> "expected the maximum initial expression\n"
  | 59 -> "expected an expression to match with\n"
  | 79 -> "expected a pattern matching case\n"
  | 80 -> "expected the name of the constructor for the enum case in the pattern matching\n"
  | 115 ->
      "expected a binding for the constructor payload, or a colon and the matching case expression\n"
  | 116 -> "expected an identifier for this enum case binding\n"
  | 83 -> "expected a colon and then the expression for this matching case\n"
  | 118 -> "expected a colon or a binding for the enum constructor payload\n"
  | 84 -> "expected an expression for this pattern matching case\n"
  | 81 ->
      "expected another match case or the rest of the expression since the previous match case is \
       complete\n"
  | 78 -> "expected the \"with patter\" keyword to complete the pattern matching expression\n"
  | 124 -> "expected the \"for\" keyword to introduce the identifier for the map predicate\n"
  | 125 -> "expected the identifier for the map predicate\n"
  | 126 -> "expected the \"in\" keyword to introduce the collection argument to map\n"
  | 127 -> "expected the collection argument to map\n"
  | 128 -> "expected the \"of\" keyword to introduce the map predicate\n"
  | 129 -> "expected an expression for the map predicate\n"
  | 54 -> "expected a collection element\n"
  | 236 -> "expected a semicolon or a right square bracket after the collection element \n"
  | 237 -> "expected another element of the collection\n"
  | 58 -> "expected an expression inside the parenthesis\n"
  | 230 -> "unmatched parenthesis that should have been closed by here\n"
  | 92 -> "expected a unit for this literal, or a valid operator to complete the expression \n"
  | 205 -> "expected an expression for the test of the conditional\n"
  | 226 -> "expected an expression the for the \"then\" branch of the conditiona\n"
  | 227 ->
      "expected the \"else\" branch of this conditional expression as the \"then\" branch is \
       complete\n"
  | 228 -> "expected an expression for the \"else\" branch of this conditional construction\n"
  | 225 -> "expected the \"then\" keyword as the conditional expression is complete\n"
  | 206 ->
      "expected the \"all\" keyword to mean the \"for all\" construction of the universal test\n"
  | 211 -> "expected an identifier for the bound variable of the universal test\n"
  | 212 -> "expected the \"in\" keyword for the rest of the universal test\n"
  | 213 -> "expected the expression designating the set on which to perform the universal test\n"
  | 214 -> "expected the \"we have\" keyword for this universal test\n"
  | 210 -> "expected an expression for the universal test\n"
  | 219 -> "expected an identifier that will designate the existential witness for the test\n"
  | 220 -> "expected the \"in\" keyword to continue this existential test\n"
  | 221 -> "expected an expression that designates the set subject to the existential test\n"
  | 222 -> "expected a keyword to form the \"such that\" expression for the existential test\n"
  | 223 -> "expected a keyword to complete the \"such that\" construction\n"
  | 217 -> "expected an expression for the existential test\n"
  | 87 -> "this is the start of an arg-maximum or arg-minimum expression\n"
  | 88 -> "expected the type of the elements compared to get the minimum\n"
  | 89 -> "expected the \"initial\" keyword introducing the initial expression for the minimum\n"
  | 90 -> "expected the initial expression for the minimum\n"
  | 199 -> "expected the type of the elements compared to get the maximum\n"
  | 200 -> "expected the \"initial\" keyword introducing the initial expression for the maximum\n"
  | 201 -> "expected the initial expression for the maximum\n"
  | 101 ->
      "expected a payload for the enum case constructor, or the rest of the expression (with an \
       operator ?)\n"
  | 102 -> "expected structure fields introduced by --\n"
  | 103 -> "expected the name of the structure field\n"
  | 107 -> "expected a colon\n"
  | 108 -> "expected the expression for this struct field\n"
  | 104 -> "expected another structure field or the closing bracket\n"
  | 105 -> "expected the name of the structure field\n"
  | 195 -> "expected an expression for the content of this enum case\n"
  | 196 ->
      "the expression for the content of the enum case is already well-formed, expected an \
       operator to form a bigger expression\n"
  | 109 -> "expected the keyword following cardinal to compute the number of elements in a set\n"
  | 243 -> "expected a scope use item: a rule, definition or assertion\n"
  | 279 -> "expected the name of the variable subject to the rule\n"
  | 256 ->
      "expected a condition or a consequence for this rule, or the rest of the variable qualified \
       name\n"
  | 286 -> "expected a condition or a consequence for this rule\n"
  | 281 -> "expected filled or not filled for a rule consequence\n"
  | 287 -> "expected the name of the parameter for this dependent variable \n"
  | 280 -> "expected the expression of the rule\n"
  | 284 -> "expected the filled keyword the this rule \n"
  | 257 -> "expected a struct field or a sub-scope context item after the dot\n"
  | 244 -> "expected the name of the label\n"
  | 274 -> "expected a rule or a definition after the label declaration\n"
  | 275 -> "expected the label to which the exception is referring back\n"
  | 278 -> "expected a rule or a definition after the exception declaration\n"
  | 291 -> "expected the name of the variable you want to define\n"
  | 292 -> "expected the defined as keyword to introduce the definition of this variable\n"
  | 294 -> "expected an expression for the consequence of this definition under condition\n"
  | 293 ->
      "expected a expression for defining this function, introduced by the defined as keyword\n"
  | 295 -> "expected an expression for the definition\n"
  | 246 -> "expected an expression that shoud be asserted during execution\n"
  | 247 -> "expecting the name of the varying variable\n"
  | 250 -> "the variable varies with an expression that was expected here\n"
  | 251 -> "expected an indication about the variation sense of the variable, or a new scope item\n"
  | 249 -> "expected an indication about what this variable varies with\n"
  | 259 -> "expected an expression for this condition\n"
  | 269 -> "expected a consequence for this definition under condition\n"
  | 265 -> "expected an expression for this definition under condition\n"
  | 261 -> "expected the name of the variable that should be fixed\n"
  | 262 -> "expected the legislative text by which the value of the variable is fixed\n"
  | 263 -> "expected the legislative text by which the value of the variable is fixed\n"
  | 272 -> "expected a new scope use item \n"
  | 302 -> "expected the kind of the declaration (struct, scope or enum)\n"
  | 303 -> "expected the struct name\n"
  | 304 -> "expected a colon\n"
  | 305 -> "expected struct data or condition\n"
  | 306 -> "expected the name of this struct data \n"
  | 307 -> "expected the type of this struct data, introduced by the content keyword\n"
  | 308 -> "expected the type of this struct data\n"
  | 322 -> "expected the name of this struct condition\n"
  | 315 -> "expected a new struct data, or another declaration or scope use\n"
  | 316 -> "expected the type of the parameter of this struct data function\n"
  | 320 -> "expected a new struct data, or another declaration or scope use\n"
  | 312 -> "expected a new struct data, or another declaration or scope use\n"
  | 325 -> "expected the name of the scope you are declaring\n"
  | 326 -> "expected a colon followed by the list of context items of this scope\n"
  | 327 -> "expected a context item introduced by \"context\"\n"
  | 328 -> "expected the name of this new context item\n"
  | 329 -> "expected the kind of this context item: is it a condition, a sub-scope or a data?\n"
  | 330 -> "expected the name of the subscope for this context item\n"
  | 337 -> "expected another scope context item or the end of the scope declaration\n"
  | 332 -> "expected the type of this context item\n"
  | 333 -> "expected the next context item or a dependency declaration for this item\n"
  | 335 -> "expected the next context item or a dependency declaration for this item\n"
  | 340 -> "expected the name of your enum\n"
  | 341 -> "expected a colon\n"
  | 342 -> "expected an enum case\n"
  | 343 -> "expected the name of an enum case \n"
  | 344 -> "expected a payload for your enum case, or another case or declaration \n"
  | 345 -> "expected a content type\n"
  | 350 -> "expected another enum case, or a new declaration or scope use\n"
  | 18 -> "expected a declaration or a scope use\n"
  | 19 -> "expected some text or the beginning of a code section\n"
  | 20 -> "expected a declaration or a scope use\n"
  | 21 -> "should not happen\n"
  | 356 -> "expected a metadata-closing tag\n"
  | 357 -> "expected a metadata-closing tag\n"
  | _ -> raise Not_found
