(** This file has been generated by the Catala compiler, do not edit! *)

open Runtime_ocaml.Runtime

[@@@ocaml.warning "-4-26-27-32-41-42"]

module S = struct
  type t = { z : integer }
end

module SIn = struct
  type t = { x_in : bool }
end

let s (s_in : SIn.t) : S.t =
  let x_ : _ = s_in.SIn.x_in in
  let f_ : _ =
    let s : _ =
     fun (env_ : _) (param_ : integer) ->
      let x_ : _ =
        let _, x = env_ in
        x
      in
      if x_ then param_ else ~-!param_
    in
    s, x_
  in
  let z_ : _ =
    let env_ : _ = f_ in
    let code_ : _ =
      let x, _ = env_ in
      x
    in
    code_ env_ (integer_of_string "-1")
  in
  { S.z = z_ }
