/* This file has been generated by the Catala compiler, do not edit! */

#ifndef __PERIOD_EN_H__
#define __PERIOD_EN_H__

#include <Period_internal.h>
#include <Date_en.h>

typedef struct PeriodEn__Period {
  CATALA_DATE PeriodEn__begin;
  CATALA_DATE PeriodEn__end;
} PeriodEn__Period;

CATALA_BOOL PeriodEn__valid (const PeriodEn__Period* p);

CATALA_DURATION PeriodEn__duration (const PeriodEn__Period* p);

CATALA_BOOL PeriodEn__are_adjacent
    (const PeriodEn__Period* p1, const PeriodEn__Period* p2);

const PeriodEn__Period* PeriodEn__join
    (const PeriodEn__Period* p1, const PeriodEn__Period* p2);

CATALA_BOOL PeriodEn__contained (const PeriodEn__Period* p, CATALA_DATE d);

const CATALA_OPTION(PeriodEn__Period*) PeriodEn__intersection
    (const PeriodEn__Period* p1, const PeriodEn__Period* p2);

const CATALA_OPTION(PeriodEn__Period*) PeriodEn__find_period
    (const CATALA_ARRAY(PeriodEn__Period*) l, CATALA_DATE d);

const CATALA_ARRAY(PeriodEn__Period*) PeriodEn__split_by_year
    (const DateEn__Month* starting_month, const PeriodEn__Period* p);

const CATALA_ARRAY(PeriodEn__Period*) PeriodEn__split_by_month
    (const PeriodEn__Period* p);

const CATALA_ARRAY(CATALA_TUPLE(PeriodEn__Period*;void * /* any t */))
    PeriodEn__sort_by_date
    (const CATALA_ARRAY(CATALA_TUPLE(PeriodEn__Period*;void * /* any t */)) l);

#endif /* __PERIOD_EN_H__ */
