/* This file has been generated by the Catala compiler, do not edit! */

#include <stdio.h>
#include <stdlib.h>
#include <catala_runtime.h>

#include <Period_internal.h>
#include <Date_en.h>

typedef struct PeriodEn__Period {
  CATALA_DATE PeriodEn__begin;
  CATALA_DATE PeriodEn__end;
} PeriodEn__Period;

CATALA_BOOL PeriodEn__valid (const PeriodEn__Period* p)
{
  CATALA_BOOL valid;
  if (o_lte_dat_dat(p->PeriodEn__end, p->PeriodEn__begin) == CATALA_TRUE) {
    valid = CATALA_FALSE;
  } else {
    valid = CATALA_TRUE;
  }
  return valid;
}

CATALA_DURATION PeriodEn__duration (const PeriodEn__Period* p)
{
  return o_sub_dat_dat(p->PeriodEn__end, p->PeriodEn__begin);
}

CATALA_BOOL PeriodEn__are_adjacent
    (const PeriodEn__Period* p1, const PeriodEn__Period* p2)
{
  return o_eq_dat_dat(p1->PeriodEn__end, p2->PeriodEn__begin);
}

static CATALA_DATE closure_join
    (const CLOSURE_ENV env, CATALA_DATE x0, CATALA_DATE x1)
{
  const CATALA_TUPLE() env__1 =
    (const CATALA_TUPLE(_))(((CATALA_TUPLE(_))env));
  return DateEn__max(x0, x1);
}

static CATALA_DATE closure_join__1
    (const CLOSURE_ENV env, CATALA_DATE x0, CATALA_DATE x1)
{
  const CATALA_TUPLE() env__1 =
    (const CATALA_TUPLE(_))(((CATALA_TUPLE(_))env));
  return DateEn__min(x0, x1);
}

const PeriodEn__Period* PeriodEn__join
    (const PeriodEn__Period* p1, const PeriodEn__Period* p2)
{
  const catala_closure* code_and_env;
  CATALA_DATE(* join__1)(const CLOSURE_ENV, CATALA_DATE, CATALA_DATE) =
    closure_join__1;
  CATALA_TUPLE() const code_and_env__2 =
    catala_malloc(0 * sizeof(tuple_element*));
  catala_closure* const code_and_env__1 =
    catala_malloc(sizeof(catala_closure));
  const catala_closure* code_and_env__3;
  CATALA_DATE(* join__2)(const CLOSURE_ENV, CATALA_DATE, CATALA_DATE) =
    closure_join;
  CATALA_TUPLE() const code_and_env__5 =
    catala_malloc(0 * sizeof(tuple_element*));
  catala_closure* const code_and_env__4 =
    catala_malloc(sizeof(catala_closure));
  PeriodEn__Period* const join = catala_malloc(sizeof(PeriodEn__Period));
  code_and_env__1->funcp = (void (*)(void))join__1;
  code_and_env__1->env = (void*)((catala_closure *)code_and_env__2);
  code_and_env = code_and_env__1;
  code_and_env__4->funcp = (void (*)(void))join__2;
  code_and_env__4->env = (void*)((catala_closure *)code_and_env__5);
  code_and_env__3 = code_and_env__4;
  join->PeriodEn__begin =
    ((CATALA_DATE(*)(const CLOSURE_ENV, CATALA_DATE, CATALA_DATE))
     code_and_env->funcp)
      (code_and_env->env, p1->PeriodEn__begin, p2->PeriodEn__begin);
  join->PeriodEn__end =
    ((CATALA_DATE(*)(const CLOSURE_ENV, CATALA_DATE, CATALA_DATE))
     code_and_env__3->funcp)
      (code_and_env__3->env, p1->PeriodEn__end, p2->PeriodEn__end);
  return join;
}

CATALA_BOOL PeriodEn__contained (const PeriodEn__Period* p, CATALA_DATE d)
{
  return catala_new_bool(*(o_lte_dat_dat(p->PeriodEn__begin, d)) &&
                         *(o_lt_dat_dat(d, p->PeriodEn__end)));
}

static const CATALA_TUPLE(CATALA_DATE;CATALA_DATE) to_tuple
    (const PeriodEn__Period* p)
{
  CATALA_TUPLE(CATALA_DATE;CATALA_DATE) const to_tuple__1 =
    catala_malloc(2 * sizeof(tuple_element*));
  to_tuple__1[0].content = p->PeriodEn__begin;
  to_tuple__1[1].content = p->PeriodEn__end;
  return to_tuple__1;
}

static const PeriodEn__Period* of_tuple (CATALA_DATE begin, CATALA_DATE end)
{
  PeriodEn__Period* const of_tuple__1 =
    catala_malloc(sizeof(PeriodEn__Period));
  of_tuple__1->PeriodEn__begin = begin;
  of_tuple__1->PeriodEn__end = end;
  return of_tuple__1;
}

static CATALA_DATE closure_intersection
    (const CLOSURE_ENV env, CATALA_DATE x0, CATALA_DATE x1)
{
  const CATALA_TUPLE() env__1 =
    (const CATALA_TUPLE(_))(((CATALA_TUPLE(_))env));
  return DateEn__min(x0, x1);
}

static CATALA_DATE closure_intersection__1
    (const CLOSURE_ENV env, CATALA_DATE x0, CATALA_DATE x1)
{
  const CATALA_TUPLE() env__1 =
    (const CATALA_TUPLE(_))(((CATALA_TUPLE(_))env));
  return DateEn__max(x0, x1);
}

const CATALA_OPTION(PeriodEn__Period*) PeriodEn__intersection
    (const PeriodEn__Period* p1, const PeriodEn__Period* p2)
{
  const PeriodEn__Period* intersection;
  const catala_closure* code_and_env;
  CATALA_DATE(* intersection__2)(const CLOSURE_ENV, CATALA_DATE, CATALA_DATE) =
    closure_intersection__1;
  CATALA_TUPLE() const code_and_env__2 =
    catala_malloc(0 * sizeof(tuple_element*));
  catala_closure* const code_and_env__1 =
    catala_malloc(sizeof(catala_closure));
  const catala_closure* code_and_env__3;
  CATALA_DATE(* intersection__3)(const CLOSURE_ENV, CATALA_DATE, CATALA_DATE) =
    closure_intersection;
  CATALA_TUPLE() const code_and_env__5 =
    catala_malloc(0 * sizeof(tuple_element*));
  catala_closure* const code_and_env__4 =
    catala_malloc(sizeof(catala_closure));
  PeriodEn__Period* const intersection__1 =
    catala_malloc(sizeof(PeriodEn__Period));
  const CATALA_OPTION(PeriodEn__Period*) intersection__4;
  code_and_env__1->funcp = (void (*)(void))intersection__2;
  code_and_env__1->env = (void*)((catala_closure *)code_and_env__2);
  code_and_env = code_and_env__1;
  code_and_env__4->funcp = (void (*)(void))intersection__3;
  code_and_env__4->env = (void*)((catala_closure *)code_and_env__5);
  code_and_env__3 = code_and_env__4;
  intersection__1->PeriodEn__begin =
    ((CATALA_DATE(*)(const CLOSURE_ENV, CATALA_DATE, CATALA_DATE))
     code_and_env->funcp)
      (code_and_env->env, p1->PeriodEn__begin, p2->PeriodEn__begin);
  intersection__1->PeriodEn__end =
    ((CATALA_DATE(*)(const CLOSURE_ENV, CATALA_DATE, CATALA_DATE))
     code_and_env__3->funcp)
      (code_and_env__3->env, p1->PeriodEn__end, p2->PeriodEn__end);
  intersection = intersection__1;
  if (PeriodEn__valid(intersection) == CATALA_TRUE) {
    intersection__4 = catala_some(intersection);
  } else {
    intersection__4 = CATALA_NONE;
  }
  return intersection__4;
}

static const CATALA_OPTION(PeriodEn__Period*) closure_find_period
    (const CLOSURE_ENV env,
     const CATALA_OPTION(PeriodEn__Period*) found,
     const PeriodEn__Period* p)
{
  const CATALA_TUPLE(CATALA_DATE) env__1 =
    (const CATALA_TUPLE(_))(((CATALA_TUPLE(_))env));
  CATALA_DATE d = (CATALA_DATE)(env__1[0].content);
  const CATALA_OPTION(PeriodEn__Period*) closure_find_period__1;
  if (found->code == catala_option_some) {
    closure_find_period__1 = found;
  } else if (PeriodEn__contained(p, d) == CATALA_TRUE) {
    closure_find_period__1 = catala_some(p);
  } else {
    closure_find_period__1 = CATALA_NONE;
  }
  return closure_find_period__1;
}

const CATALA_OPTION(PeriodEn__Period*) PeriodEn__find_period
    (const CATALA_ARRAY(PeriodEn__Period*) l, CATALA_DATE d)
{
  const CATALA_OPTION(PeriodEn__Period*)(* find_period)
      (const CLOSURE_ENV, const CATALA_OPTION(PeriodEn__Period*),
       const PeriodEn__Period*) = closure_find_period;
  CATALA_TUPLE(CATALA_DATE) const find_period__2 =
    catala_malloc(1 * sizeof(tuple_element*));
  catala_closure* const find_period__1 =
    catala_malloc(sizeof(catala_closure));
  const CATALA_OPTION(PeriodEn__Period*) find_period__3 = CATALA_NONE;
  find_period__2[0].content = d;
  find_period__1->funcp = (void (*)(void))find_period;
  find_period__1->env = (void*)((catala_closure *)find_period__2);
  return ((const CATALA_OPTION(PeriodEn__Period*))o_fold(find_period__1,
    find_period__3, l));
}

static const CATALA_TUPLE(CATALA_DATE;CATALA_DATE) closure_to_tuple_list
    (const CLOSURE_ENV env, const PeriodEn__Period* p)
{
  const CATALA_TUPLE() env__1 =
    (const CATALA_TUPLE(_))(((CATALA_TUPLE(_))env));
  return to_tuple(p);
}

static const CATALA_ARRAY(CATALA_TUPLE(CATALA_DATE;CATALA_DATE))
    to_tuple_list (const CATALA_ARRAY(PeriodEn__Period*) l)
{
  const CATALA_TUPLE(CATALA_DATE;CATALA_DATE)(* to_tuple_list__1)
      (const CLOSURE_ENV, const PeriodEn__Period*) = closure_to_tuple_list;
  CATALA_TUPLE() const to_tuple_list__3 =
    catala_malloc(0 * sizeof(tuple_element*));
  catala_closure* const to_tuple_list__2 =
    catala_malloc(sizeof(catala_closure));
  to_tuple_list__2->funcp = (void (*)(void))to_tuple_list__1;
  to_tuple_list__2->env = (void*)((catala_closure *)to_tuple_list__3);
  return o_map(to_tuple_list__2, l);
}

static const CATALA_TUPLE(CATALA_TUPLE(CATALA_DATE;CATALA_DATE);void * /* any t */)
    closure_to_tuple_associated_list
    (const CLOSURE_ENV env,
     const CATALA_TUPLE(PeriodEn__Period*;void * /* any t */) p)
{
  const CATALA_TUPLE() env__1 =
    (const CATALA_TUPLE(_))(((CATALA_TUPLE(_))env));
  CATALA_TUPLE(CATALA_TUPLE(CATALA_DATE;CATALA_DATE);void * /* any t */) const
    closure_to_tuple_associated_list__1 =
    catala_malloc(2 * sizeof(tuple_element*));
  closure_to_tuple_associated_list__1[0].content =
    to_tuple((PeriodEn__Period*)(p[0].content));
  closure_to_tuple_associated_list__1[1].content =
    (void * /* any t */)(p[1].content);
  return closure_to_tuple_associated_list__1;
}

static const CATALA_ARRAY(CATALA_TUPLE(CATALA_TUPLE(CATALA_DATE;CATALA_DATE);void * /* any t */))
    to_tuple_associated_list
    (const CATALA_ARRAY(CATALA_TUPLE(PeriodEn__Period*;void * /* any t */)) l)
{
  const CATALA_TUPLE(CATALA_TUPLE(CATALA_DATE;CATALA_DATE);void * /* any t */)(*
      to_tuple_associated_list__1)
      (const CLOSURE_ENV,
       const CATALA_TUPLE(PeriodEn__Period*;void * /* any t */)) =
    closure_to_tuple_associated_list;
  CATALA_TUPLE() const to_tuple_associated_list__3 =
    catala_malloc(0 * sizeof(tuple_element*));
  catala_closure* const to_tuple_associated_list__2 =
    catala_malloc(sizeof(catala_closure));
  to_tuple_associated_list__2[0].content = to_tuple_associated_list__1;
  to_tuple_associated_list__2[1].content =
    ((catala_closure *)to_tuple_associated_list__3);
  return o_map(to_tuple_associated_list__2, l);
}

static const PeriodEn__Period* closure_of_tuple_list
    (const CLOSURE_ENV env, const CATALA_TUPLE(CATALA_DATE;CATALA_DATE) tpl)
{
  const CATALA_TUPLE() env__1 =
    (const CATALA_TUPLE(_))(((CATALA_TUPLE(_))env));
  return of_tuple
           ((CATALA_DATE)(tpl[0].content), (CATALA_DATE)(tpl[1].content));
}

static const CATALA_ARRAY(PeriodEn__Period*) of_tuple_list
    (const CATALA_ARRAY(CATALA_TUPLE(CATALA_DATE;CATALA_DATE)) l)
{
  const PeriodEn__Period*(* of_tuple_list__1)
      (const CLOSURE_ENV, const CATALA_TUPLE(CATALA_DATE;CATALA_DATE)) =
    closure_of_tuple_list;
  CATALA_TUPLE() const of_tuple_list__3 =
    catala_malloc(0 * sizeof(tuple_element*));
  catala_closure* const of_tuple_list__2 =
    catala_malloc(sizeof(catala_closure));
  of_tuple_list__2->funcp = (void (*)(void))of_tuple_list__1;
  of_tuple_list__2->env = (void*)((catala_closure *)of_tuple_list__3);
  return o_map(of_tuple_list__2, l);
}

static const CATALA_TUPLE(PeriodEn__Period*;void * /* any t */)
    closure_of_tuple_associated_list
    (const CLOSURE_ENV env,
     const CATALA_TUPLE(CATALA_TUPLE(CATALA_DATE;CATALA_DATE);void * /* any t */)
       tpl)
{
  const CATALA_TUPLE() env__1 =
    (const CATALA_TUPLE(_))(((CATALA_TUPLE(_))env));
  const CATALA_TUPLE(CATALA_DATE;CATALA_DATE) args =
    (CATALA_TUPLE(CATALA_DATE;CATALA_DATE))(tpl[0].content);
  CATALA_TUPLE(PeriodEn__Period*;void * /* any t */) const
    closure_of_tuple_associated_list__1 =
    catala_malloc(2 * sizeof(tuple_element*));
  closure_of_tuple_associated_list__1[0].content =
    of_tuple((CATALA_DATE)(args[0].content), (CATALA_DATE)(args[1].content));
  closure_of_tuple_associated_list__1[1].content =
    (void * /* any t */)(tpl[1].content);
  return closure_of_tuple_associated_list__1;
}

static const CATALA_ARRAY(CATALA_TUPLE(PeriodEn__Period*;void * /* any t */))
    of_tuple_associated_list
    (const CATALA_ARRAY(CATALA_TUPLE(CATALA_TUPLE(CATALA_DATE;CATALA_DATE);void * /* any t */))
       l)
{
  const CATALA_TUPLE(PeriodEn__Period*;void * /* any t */)(*
      of_tuple_associated_list__1)
      (const CLOSURE_ENV,
       const CATALA_TUPLE(CATALA_TUPLE(CATALA_DATE;CATALA_DATE);void * /* any t */)) =
    closure_of_tuple_associated_list;
  CATALA_TUPLE() const of_tuple_associated_list__3 =
    catala_malloc(0 * sizeof(tuple_element*));
  catala_closure* const of_tuple_associated_list__2 =
    catala_malloc(sizeof(catala_closure));
  of_tuple_associated_list__2[0].content = of_tuple_associated_list__1;
  of_tuple_associated_list__2[1].content =
    ((catala_closure *)of_tuple_associated_list__3);
  return o_map(of_tuple_associated_list__2, l);
}

static const CATALA_ARRAY(CATALA_TUPLE(CATALA_DATE;CATALA_DATE))
    closure_split_by_year
    (const CLOSURE_ENV env,
     CATALA_INT x0,
     const CATALA_TUPLE(CATALA_DATE;CATALA_DATE) x1)
{
  const CATALA_TUPLE() env__1 =
    (const CATALA_TUPLE(_))(((CATALA_TUPLE(_))env));
  return PeriodInternal__split_by_year(x0, x1);
}

static CATALA_INT closure_split_by_year__1
    (const CLOSURE_ENV env, const DateEn__Month* x0)
{
  const CATALA_TUPLE() env__1 =
    (const CATALA_TUPLE(_))(((CATALA_TUPLE(_))env));
  return DateEn__month_to_int(x0);
}

const CATALA_ARRAY(PeriodEn__Period*) PeriodEn__split_by_year
    (const DateEn__Month* starting_month, const PeriodEn__Period* p)
{
  const catala_closure* code_and_env;
  const CATALA_ARRAY(CATALA_TUPLE(CATALA_DATE;CATALA_DATE))(* split_by_year)
      (const CLOSURE_ENV, CATALA_INT,
       const CATALA_TUPLE(CATALA_DATE;CATALA_DATE)) = closure_split_by_year;
  CATALA_TUPLE() const code_and_env__2 =
    catala_malloc(0 * sizeof(tuple_element*));
  catala_closure* const code_and_env__1 =
    catala_malloc(sizeof(catala_closure));
  const catala_closure* code_and_env__3;
  CATALA_INT(* split_by_year__1)(const CLOSURE_ENV, const DateEn__Month*) =
    closure_split_by_year__1;
  CATALA_TUPLE() const code_and_env__5 =
    catala_malloc(0 * sizeof(tuple_element*));
  catala_closure* const code_and_env__4 =
    catala_malloc(sizeof(catala_closure));
  code_and_env__1->funcp = (void (*)(void))split_by_year;
  code_and_env__1->env = (void*)((catala_closure *)code_and_env__2);
  code_and_env = code_and_env__1;
  code_and_env__4->funcp = (void (*)(void))split_by_year__1;
  code_and_env__4->env = (void*)((catala_closure *)code_and_env__5);
  code_and_env__3 = code_and_env__4;
  return of_tuple_list
           (((const CATALA_ARRAY(CATALA_TUPLE(CATALA_DATE;CATALA_DATE))(*)
                  (const CLOSURE_ENV, CATALA_INT,
                   const CATALA_TUPLE(CATALA_DATE;CATALA_DATE)))
             code_and_env->funcp)
              (code_and_env->env,
               ((CATALA_INT(*)(const CLOSURE_ENV, const DateEn__Month*))
                code_and_env__3->funcp)(code_and_env__3->env, starting_month),
               to_tuple(p)));
}

static const CATALA_ARRAY(CATALA_TUPLE(CATALA_DATE;CATALA_DATE))
    closure_split_by_month
    (const CLOSURE_ENV env, const CATALA_TUPLE(CATALA_DATE;CATALA_DATE) x0)
{
  const CATALA_TUPLE() env__1 =
    (const CATALA_TUPLE(_))(((CATALA_TUPLE(_))env));
  return PeriodInternal__split_by_month(x0);
}

const CATALA_ARRAY(PeriodEn__Period*) PeriodEn__split_by_month
    (const PeriodEn__Period* p)
{
  const catala_closure* code_and_env;
  const CATALA_ARRAY(CATALA_TUPLE(CATALA_DATE;CATALA_DATE))(* split_by_month)
      (const CLOSURE_ENV, const CATALA_TUPLE(CATALA_DATE;CATALA_DATE)) =
    closure_split_by_month;
  CATALA_TUPLE() const code_and_env__2 =
    catala_malloc(0 * sizeof(tuple_element*));
  catala_closure* const code_and_env__1 =
    catala_malloc(sizeof(catala_closure));
  code_and_env__1->funcp = (void (*)(void))split_by_month;
  code_and_env__1->env = (void*)((catala_closure *)code_and_env__2);
  code_and_env = code_and_env__1;
  return of_tuple_list
           (((const CATALA_ARRAY(CATALA_TUPLE(CATALA_DATE;CATALA_DATE))(*)
                  (const CLOSURE_ENV,
                   const CATALA_TUPLE(CATALA_DATE;CATALA_DATE)))
             code_and_env->funcp)(code_and_env->env, to_tuple(p)));
}

static const CATALA_ARRAY(CATALA_TUPLE(CATALA_TUPLE(CATALA_DATE;CATALA_DATE);void * /* any t */))
    closure_sort_by_date
    (const CLOSURE_ENV env,
     const CATALA_ARRAY(CATALA_TUPLE(CATALA_TUPLE(CATALA_DATE;CATALA_DATE);void * /* any t */))
       x0)
{
  const CATALA_TUPLE() env__1 =
    (const CATALA_TUPLE(_))(((CATALA_TUPLE(_))env));
  return PeriodInternal__sort(x0);
}

const CATALA_ARRAY(CATALA_TUPLE(PeriodEn__Period*;void * /* any t */))
    PeriodEn__sort_by_date
    (const CATALA_ARRAY(CATALA_TUPLE(PeriodEn__Period*;void * /* any t */)) l)
{
  const CATALA_ARRAY(CATALA_TUPLE(CATALA_TUPLE(CATALA_DATE;CATALA_DATE);void * /* any t */))
    tuple_associated_list = to_tuple_associated_list(l);
  const CATALA_ARRAY(CATALA_TUPLE(CATALA_TUPLE(CATALA_DATE;CATALA_DATE);void * /* any t */))
    sorted_tuple_associated_list;
  const catala_closure* code_and_env;
  const CATALA_ARRAY(CATALA_TUPLE(CATALA_TUPLE(CATALA_DATE;CATALA_DATE);void * /* any t */))(*
      sort_by_date)
      (const CLOSURE_ENV,
       const CATALA_ARRAY(CATALA_TUPLE(CATALA_TUPLE(CATALA_DATE;CATALA_DATE);void * /* any t */))) =
    closure_sort_by_date;
  CATALA_TUPLE() const code_and_env__2 =
    catala_malloc(0 * sizeof(tuple_element*));
  catala_closure* const code_and_env__1 =
    catala_malloc(sizeof(catala_closure));
  code_and_env__1[0].content = sort_by_date;
  code_and_env__1[1].content = ((catala_closure *)code_and_env__2);
  code_and_env = code_and_env__1;
  sorted_tuple_associated_list = ((const CATALA_ARRAY(CATALA_TUPLE(CATALA_TUPLE(CATALA_DATE;CATALA_DATE);void * /* any t */))(*)
                                       (const CLOSURE_ENV,
                                        const CATALA_ARRAY(CATALA_TUPLE(CATALA_TUPLE(CATALA_DATE;CATALA_DATE);void * /* any t */))))
                                  code_and_env->funcp)
                                   (code_and_env->env, tuple_associated_list);
  return of_tuple_associated_list(sorted_tuple_associated_list);
}

