[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "catala_ro_lexer"
version = "0.8"
dependencies = ["pygments"]

[project.entry-points."pygments.lexers"]
catala-ro-lexer = "catala_ro_lexer.lexer:CustomLexer"
