# This file has been generated by the Catala compiler, do not edit!

from catala_runtime import *
from typing import Any, List, Callable, Tuple
from enum import Enum

# Fixme: at the moment this and the corresponding part of the runtime
# are still based on the Python date module and not on Dates_calc

def of_ymd(pos:SourcePosition, dyear:Integer, dmonth:Integer, dday:Integer):
    try:
        return Date(datetime.date(int(dyear.value), int(dmonth.value), int(dday.value)))
    except InvalidDate:
        raise AssertionFailed(pos)

def to_ymd(d:Date):
    return (integer_of_int(d.value.year),
            integer_of_int(d.value.month),
            integer_of_int(d.value.day))

def last_day_of_month(d:Date):
    return Date(datetime.date(d.value.year, d.value.month, calendar.monthrange(d.value.year, d.value.month)[1]))

def add_rounded_down(d:Date, dur:Duration):
    return add_date_duration(RoundDown)(d, dur)

def add_rounded_up(d:Date, dur:Duration):
    return add_date_duration(RoundUp)(d, dur)
