# This file has been generated by the Catala compiler, do not edit!

from catala_runtime import *
from enum import Enum

# Fixme: at the moment this and the corresponding part of the runtime
# are still based on the Python date module and not on Dates_calc

def of_ymd(pos:SourcePosition, dyear:Integer, dmonth:Integer, dday:Integer) -> Date:
    return Date((dyear, dmonth, dday), pos)

def to_ymd(d:Date) -> CatalaTuple[Integer, Integer, Integer]:
    return CatalaTuple(Integer(d.value.year),
                       Integer(d.value.month),
                       Integer(d.value.day))

def last_day_of_month(d:Date) -> Date:
    return Date(d.value.last_day_of_month())

def add_rounded_down(d:Date, dur:Duration) -> Date:
    return d.__add__(dur, dates.DateRounding.RoundDown)

def add_rounded_up(d:Date, dur:Duration) -> Date:
    return d.__add__(dur, dates.DateRounding.RoundUp)
