# This file has been generated by the Catala compiler, do not edit!

from catala_runtime import *
from typing import Any, List, Callable, Tuple
from enum import Enum

# Fixme: at the moment this and the corresponding part of the runtime
# are still based on the Python date module and not on Dates_calc

def of_ymd(pos:SourcePosition, dyear:Integer, dmonth:Integer, dday:Integer):
    return Date((dyear.value, dmonth.value, dday.value), pos)

def to_ymd(d:Date):
    return (Integer(d.value.year),
            Integer(d.value.month),
            Integer(d.value.day))

def last_day_of_month(d:Date):
    return Date(d.value.last_day_of_month())

def add_rounded_down(d:Date, dur:Duration):
    return d.__add__(dur, dates.DateRounding.RoundDown)

def add_rounded_up(d:Date, dur:Duration):
    return d.__add__(dur, dates.DateRounding.RoundUp)
