(** This file has been generated by the Catala compiler, do not edit! *)

open Runtime_ocaml.Runtime

[@@@ocaml.warning "-4-26-27-32-41-42"]

module A = struct
  type t = {w: integer}
end

module AIn = struct
  type t = unit
end



let a (a_in: AIn.t) : A.t =
  let w_: integer = Eoption.ESome
                      (o_add_int_int
                         (o_add_int_int (integer_of_string "1")
                            (integer_of_string "2")) (integer_of_string "3")) in
  Eoption.ESome ({A.w = w_})
