(* This file has been generated, do not edit manually. *)

(* Defining the lexer macros for french *)

(* Tokens *)

#define MS_ALL "tout"
#define MS_AMONG "parmi"
#define MS_AND "et"
#define MS_AND_THEN "puis"
#define MS_ASSERTION "assertion"
#define MS_BUT_REPLACE "mais en remplaçant"
#define MR_BUT_REPLACE "mais", space_plus, "en", space_plus, "rempla", 0xe7, "ant"
#define MS_COMBINE "combine"
#define MS_CONDITION "condition"
#define MS_CONSEQUENCE "conséquence"
#define MR_CONSEQUENCE "cons", 0xe9, "quence"
#define MS_CONTAINS "contient"
#define MS_CONTENT "contenu"
#define MS_CONTEXT "contexte"
#define MS_DATA "donnée"
#define MR_DATA "donn", 0xe9, 'e'
#define MS_DAY "jour"
#define MS_DECLARATION "déclaration"
#define MR_DECLARATION 'd', 0xe9, "claration"
#define MS_DECREASING "inférieur"
#define MR_DECREASING "inf", 0xe9, "rieur"
#define MS_DEFINED_AS "égal à"
#define MR_DEFINED_AS 0xe9, "gal", space_plus, 0xe0
#define MS_DEFINITION "définition"
#define MR_DEFINITION 'd', 0xe9, "finition"
#define MS_DEPENDS "dépend de"
#define MR_DEPENDS 'd', 0xe9, "pend", space_plus, "de"
#define MS_ELSE "sinon"
#define MS_ENUM "énumération"
#define MR_ENUM 0xe9, "num", 0xe9, "ration"
#define MS_EXCEPTION "exception"
#define MS_EXISTS "existe"
#define MS_FALSE "faux"
#define MS_FILLED "rempli"
#define MS_FOR "pour"
#define MS_IF "si"
#define MS_IN "dans"
#define MS_INCREASING "supérieur"
#define MR_INCREASING "sup", 0xe9, "rieur"
#define MS_INITIALLY "initialement"
#define MS_INPUT "entrée"
#define MR_INPUT "entr", 0xe9, 'e'
#define MS_INTERNAL "interne"
#define MS_IS "est"
#define MS_LABEL "étiquette"
#define MR_LABEL 0xe9, "tiquette"
#define MS_LET "soit"
#define MS_LIST "liste de"
#define MR_LIST "liste", space_plus, "de"
#define MS_MAP_EACH "transforme chaque"
#define MR_MAP_EACH "transforme", space_plus, "chaque"
#define MS_MATCH "selon"
#define MS_MAXIMUM "maximum"
#define MS_MINIMUM "minimum"
#define MS_MONTH "mois"
#define MS_NOT "non"
#define MS_OF "de"
#define MS_OPTION "optionnel de"
#define MR_OPTION "optionnel", space_plus, "de"
#define MS_OR "ou"
#define MS_OR_IF_LIST_EMPTY "ou si liste vide"
#define MR_OR_IF_LIST_EMPTY "ou", space_plus, "si", space_plus, "liste", space_plus, "vide"
#define MS_ORDER_ASCENDING "par ordre croissant"
#define MR_ORDER_ASCENDING "par", space_plus, "ordre", space_plus, "croissant"
#define MS_ORDER_DESCENDING "par ordre décroissant"
#define MR_ORDER_DESCENDING "par", space_plus, "ordre", space_plus, 'd', 0xe9, "croissant"
#define MS_OUTPUT "résultat"
#define MR_OUTPUT 'r', 0xe9, "sultat"
#define MS_RULE "règle"
#define MR_RULE 'r', 0xe8, "gle"
#define MS_SCOPE "champ d'application"
#define MR_SCOPE "champ", space_plus, "d'application"
#define MS_SORT "trie"
#define MS_STATE "état"
#define MR_STATE 0xe9, "tat"
#define MS_STRUCT "structure"
#define MS_SUCH "tel"
#define MS_SUM "somme"
#define MS_THAT "que"
#define MS_THEN "alors"
#define MS_TO "en"
#define MS_TRUE "vrai"
#define MS_TYPE "type"
#define MS_UNDER_CONDITION "sous condition"
#define MR_UNDER_CONDITION "sous", space_plus, "condition"
#define MS_WE_HAVE "on a"
#define MR_WE_HAVE "on", space_plus, 'a'
#define MS_WILDCARD "n'importe quel"
#define MR_WILDCARD "n'importe", space_plus, "quel"
#define MS_WITH "sous forme"
#define MR_WITH "sous", space_plus, "forme"
#define MS_WITH_V "avec"
#define MS_XOR "ou bien"
#define MR_XOR "ou", space_plus, "bien"
#define MS_YEAR "an"

(* Specific delimiters *)

#define MC_DECIMAL_SEPARATOR ','
#define MR_MONEY_DELIM ' '
#define MS_MONEY_OP_SUFFIX "€"
#define MR_MONEY_OP_SUFFIX 0x20ac
#define MR_MONEY_PREFIX ""
#define MR_MONEY_SUFFIX Star hspace, 0x20ac

(* Builtins *)

#define MS_BOOLEAN "booléen"
#define MR_BOOLEAN "bool", 0xe9, "en"
#define MS_DATE "date"
#define MS_DECIMAL "décimal"
#define MR_DECIMAL 'd', 0xe9, "cimal"
#define MS_DURATION "durée"
#define MR_DURATION "dur", 0xe9, 'e'
#define MS_INTEGER "entier"
#define MS_MONEY "argent"
#define MS_POSITION "position_source"
#define MS_PRESENT "Présent"
#define MR_PRESENT "Pr", 0xe9, "sent"
#define MS_ABSENT "Absent"
#define MS_ROUND "arrondi"
#define MS_IMPOSSIBLE "impossible"
#define MS_CARDINAL "nombre"

(* Directives *)

#define MR_EXTERNAL "externe"
#define MR_LAW_INCLUDE "Inclusion"
#define MR_MODULE_ALIAS "en", space_plus, "tant", space_plus, "que"
#define MR_MODULE_DEF "Module"
#define MR_MODULE_USE "Usage", space_plus, "de"