(* This file has been generated, do not edit manually. *)

(* Defining the lexer macros for polish *)

(* Keywords *)

#define MS_ALL "wszystkie"
#define MS_AMONG "wśród"
#define MR_AMONG 'w', 0x15b, 'r', 0xf3, 'd'
#define MS_AND "i"
#define MS_AND_THEN "and then"
#define MR_AND_THEN "and", space_plus, "then"
#define MS_ASSERTION "asercja"
#define MS_BUT_REPLACE "ale zastąpić"
#define MR_BUT_REPLACE "ale", space_plus, "zast", 0x105, "pi", 0x107
#define MS_COMBINE "połączyć"
#define MR_COMBINE "po", 0x142, 0x105, "czy", 0x107
#define MS_CONDITION "warunek"
#define MS_CONSEQUENCE "konsekwencja"
#define MS_CONTAINS "zawiera"
#define MS_CONTENT "typu"
#define MS_CONTEXT "kontekst"
#define MS_DATA "dane"
#define MS_DAY "dzień"
#define MR_DAY "dzie", 0x144
#define MS_DECLARATION "deklaracja"
#define MS_DECREASING "dół"
#define MR_DECREASING 'd', 0xf3, 0x142
#define MS_DEFINED_AS "wynosi"
#define MS_DEFINITION "definicja"
#define MS_DEPENDS "zależy od"
#define MR_DEPENDS "zale", 0x17c, 'y', space_plus, "od"
#define MS_ELSE "inaczej"
#define MS_ENUM "enumeracja"
#define MS_EXCEPTION "wyjątek"
#define MR_EXCEPTION "wyj", 0x105, "tek"
#define MS_EXISTS "istnieje"
#define MS_FALSE "fałsz"
#define MR_FALSE "fa", 0x142, "sz"
#define MS_FILLED "spełnione"
#define MR_FILLED "spe", 0x142, "nione"
#define MS_FOR "dla"
#define MS_IF "jeżeli"
#define MR_IF "je", 0x17c, "eli"
#define MS_IN "w"
#define MS_INCREASING "górę"
#define MR_INCREASING 'g', 0xf3, 'r', 0x119
#define MS_INITIALLY "początkowo"
#define MR_INITIALLY "pocz", 0x105, "tkowo"
#define MS_INPUT "wejście"
#define MR_INPUT "wej", 0x15b, "cie"
#define MS_INTERNAL "wewnętrzny"
#define MR_INTERNAL "wewn", 0x119, "trzny"
#define MS_IS "jest"
#define MS_LABEL "etykieta"
#define MS_LET "niech"
#define MS_LIST "lista"
#define MS_MAP_EACH "plan każdy"
#define MR_MAP_EACH "plan", space_plus, "ka", 0x17c, "dy"
#define MS_MATCH "pasuje"
#define MS_MAXIMUM "maksimum"
#define MS_MINIMUM "minimum"
#define MS_MONTH "miesiąc"
#define MR_MONTH "miesi", 0x105, 'c'
#define MS_NOT "nie"
#define MS_OF "z"
#define MS_OPTION "opcjonalny"
#define MS_OR "lub"
#define MS_OR_IF_LIST_EMPTY "lub jeżeli lista pusta"
#define MR_OR_IF_LIST_EMPTY "lub", space_plus, "je", 0x17c, "eli", space_plus, "lista", space_plus, "pusta"
#define MS_ORDER_ASCENDING "by increasing order"
#define MR_ORDER_ASCENDING "by", space_plus, "increasing", space_plus, "order"
#define MS_ORDER_DESCENDING "by decreasing order"
#define MR_ORDER_DESCENDING "by", space_plus, "decreasing", space_plus, "order"
#define MS_OUTPUT "wyjście"
#define MR_OUTPUT "wyj", 0x15b, "cie"
#define MS_RULE "zasada"
#define MS_SCOPE "zakres"
#define MS_SORT "sort"
#define MS_STATE "stan"
#define MS_STRUCT "struktura"
#define MS_SUCH "takie że"
#define MR_SUCH "takie", space_plus, 0x17c, 'e'
#define MS_SUM "suma"
#define MS_THAT "to"
#define MS_THEN "wtedy"
#define MS_TO "do"
#define MS_TRUE "prawda"
#define MS_TYPE "rodzaj"
#define MS_UNDER_CONDITION "pod warunkiem"
#define MR_UNDER_CONDITION "pod", space_plus, "warunkiem"
#define MS_WE_HAVE "mamy"
#define MS_WILDCARD "cokolwiek"
#define MS_WITH "ze wzorem"
#define MR_WITH "ze", space_plus, "wzorem"
#define MS_WITH_V "wraz z"
#define MR_WITH_V "wraz", space_plus, 'z'
#define MS_XOR "albo"
#define MS_YEAR "rok"

(* Specific delimiters *)

#define MC_DECIMAL_SEPARATOR '.'
#define MR_MONEY_DELIM ','
#define MS_MONEY_OP_SUFFIX "PLN"
#define MR_MONEY_PREFIX ""
#define MR_MONEY_SUFFIX Star hspace, "PLN"

(* Builtins *)

#define MS_BOOLEAN "zerojedynkowy"
#define MS_DATE "czas"
#define MS_DECIMAL "dziesiętny"
#define MR_DECIMAL "dziesi", 0x119, "tny"
#define MS_DURATION "czastrwania"
#define MS_INTEGER "całkowita"
#define MR_INTEGER "ca", 0x142, "kowita"
#define MS_MONEY "pieniądze"
#define MR_MONEY "pieni", 0x105, "dze"
#define MS_POSITION "code_location"
#define MS_PRESENT "Obecny"
#define MS_ABSENT "Nieobecny"
#define MS_ROUND "zaokrąglony"
#define MR_ROUND "zaokr", 0x105, "glony"
#define MS_IMPOSSIBLE "niemożliwe"
#define MR_IMPOSSIBLE "niemo", 0x17c, "liwe"
#define MS_CARDINAL "liczba"

(* Directives *)

#define MR_EXTERNAL "external"
#define MR_LAW_INCLUDE "Include"
#define MR_MODULE_ALIAS "as"
#define MR_MODULE_DEF "Module"
#define MR_MODULE_USE "Using"