(* This file has been generated, do not edit manually. *)

(* Defining the lexer macros for english *)

(* Tokens *)

#define MS_ALL "all"
#define MS_AMONG "among"
#define MS_AND "and"
#define MS_AND_THEN "and then"
#define MR_AND_THEN "and", space_plus, "then"
#define MS_ASSERTION "assertion"
#define MS_BUT_REPLACE "but replace"
#define MR_BUT_REPLACE "but", space_plus, "replace"
#define MS_COMBINE "combine"
#define MS_CONDITION "condition"
#define MS_CONSEQUENCE "consequence"
#define MS_CONTAINS "contains"
#define MS_CONTENT "content"
#define MS_CONTEXT "context"
#define MS_DATA "data"
#define MS_DAY "day"
#define MS_DECLARATION "declaration"
#define MS_DECREASING "down"
#define MS_DEFINED_AS "equals"
#define MS_DEFINITION "definition"
#define MS_DEPENDS "depends on"
#define MR_DEPENDS "depends", space_plus, "on"
#define MS_ELSE "else"
#define MS_ENUM "enumeration"
#define MS_EXCEPTION "exception"
#define MS_EXISTS "exists"
#define MS_FALSE "false"
#define MS_FILLED "fulfilled"
#define MS_FOR "for"
#define MS_IF "if"
#define MS_IN "in"
#define MS_INCREASING "up"
#define MS_INITIALLY "initially"
#define MS_INPUT "input"
#define MS_INTERNAL "internal"
#define MS_IS "is"
#define MS_LABEL "label"
#define MS_LET "let"
#define MS_LIST "list of"
#define MR_LIST "list", space_plus, "of"
#define MS_MAP_EACH "map each"
#define MR_MAP_EACH "map", space_plus, "each"
#define MS_MATCH "match"
#define MS_MAXIMUM "maximum"
#define MS_MINIMUM "minimum"
#define MS_MONTH "month"
#define MS_NOT "not"
#define MS_OF "of"
#define MS_OPTION "optional of"
#define MR_OPTION "optional", space_plus, "of"
#define MS_OR "or"
#define MS_OR_IF_LIST_EMPTY "or if list empty"
#define MR_OR_IF_LIST_EMPTY "or", space_plus, "if", space_plus, "list", space_plus, "empty"
#define MS_ORDER_ASCENDING "in increasing order"
#define MR_ORDER_ASCENDING "in", space_plus, "increasing", space_plus, "order"
#define MS_ORDER_DESCENDING "in decreasing order"
#define MR_ORDER_DESCENDING "in", space_plus, "decreasing", space_plus, "order"
#define MS_OUTPUT "output"
#define MS_RULE "rule"
#define MS_SCOPE "scope"
#define MS_SORT "sort"
#define MS_STATE "state"
#define MS_STRUCT "structure"
#define MS_SUCH "such"
#define MS_SUM "sum"
#define MS_THAT "that"
#define MS_THEN "then"
#define MS_TO "to"
#define MS_TRUE "true"
#define MS_TYPE "type"
#define MS_UNDER_CONDITION "under condition"
#define MR_UNDER_CONDITION "under", space_plus, "condition"
#define MS_WE_HAVE "we have"
#define MR_WE_HAVE "we", space_plus, "have"
#define MS_WILDCARD "anything"
#define MS_WITH "with pattern"
#define MR_WITH "with", space_plus, "pattern"
#define MS_WITH_V "with"
#define MS_XOR "xor"
#define MS_YEAR "year"

(* Specific delimiters *)

#define MC_DECIMAL_SEPARATOR '.'
#define MR_MONEY_DELIM ','
#define MS_MONEY_OP_SUFFIX "$"
#define MR_MONEY_PREFIX '$', Star hspace
#define MR_MONEY_SUFFIX ""

(* Builtins *)

#define MS_BOOLEAN "boolean"
#define MS_DATE "date"
#define MS_DECIMAL "decimal"
#define MS_DURATION "duration"
#define MS_INTEGER "integer"
#define MS_MONEY "money"
#define MS_POSITION "code_location"
#define MS_PRESENT "Present"
#define MS_ABSENT "Absent"
#define MS_ROUND "round"
#define MS_IMPOSSIBLE "impossible"
#define MS_CARDINAL "number"

(* Directives *)

#define MR_EXTERNAL "external"
#define MR_LAW_INCLUDE "Include"
#define MR_MODULE_ALIAS "as"
#define MR_MODULE_DEF "Module"
#define MR_MODULE_USE "Using"