/* This file has been generated by the Catala compiler, do not edit! */

#include <stdio.h>
#include <stdlib.h>
#include <runtime.c>


typedef struct Foo {
  CATALA_BOOL x;
  CATALA_DEC y;
} Foo;

typedef struct Baz {
  CATALA_DEC b;
  const CATALA_ARRAY(CATALA_DEC) c;
} Baz;

enum Bar_code {
  Bar_No,
  Bar_Yes
} Bar_code;

typedef struct Bar {
  enum Bar_code code;
  union {
    CATALA_UNIT No;
    const Foo* Yes;
  } payload;
} Bar;

typedef struct Baz_in {
  const catala_closure* a_in;
} Baz_in;

const Baz* baz (const Baz_in* baz_in)
{
  static const catala_code_position pos[1] =
    {{"tests/backends/simple.catala_en", 11, 11, 11, 12}};
  static const catala_code_position pos[1] =
    {{"tests/backends/simple.catala_en", 12, 10, 12, 11}};
  static const catala_code_position pos[1] =
    {{"tests/backends/simple.catala_en", 13, 10, 13, 11}};
  static const catala_code_position pos[1] =
    {{"tests/backends/simple.catala_en", 25, 22, 25, 26}};
  static const catala_code_position pos[1] =
    {{"tests/backends/simple.catala_en", 27, 23, 27, 28}};
  const catala_closure* a;
  const Bar* a2;
  const CATALA_OPTION(Bar*) a3;
  const catala_closure* code_and_env;
  CATALA_ARRAY(CATALA_OPTION(Bar*)) a3 = catala_malloc(sizeof(catala_array));
  const CATALA_OPTION(Bar*) a4;
  const Bar* a1;
  CATALA_DEC b2;
  const CATALA_OPTION(CATALA_DEC) b3;
  const CATALA_OPTION(CATALA_DEC) b4;
  const CATALA_OPTION(CATALA_DEC) b5;
  CATALA_ARRAY(CATALA_OPTION(CATALA_DEC)) b6 =
    catala_malloc(sizeof(catala_array));
  const CATALA_OPTION(CATALA_DEC) b7;
  CATALA_ARRAY(CATALA_OPTION(CATALA_DEC)) b8 =
    catala_malloc(sizeof(catala_array));
  const CATALA_OPTION(CATALA_DEC) b9;
  CATALA_ARRAY(CATALA_OPTION(CATALA_DEC)) b10 =
    catala_malloc(sizeof(catala_array));
  const CATALA_OPTION(CATALA_DEC) b11;
  CATALA_DEC b1;
  const CATALA_ARRAY(CATALA_DEC) c2;
  const CATALA_OPTION(CATALA_ARRAY(CATALA_DEC)) c3;
  const CATALA_OPTION(CATALA_ARRAY(CATALA_DEC)) c4;
  CATALA_ARRAY(CATALA_OPTION(CATALA_ARRAY(CATALA_DEC))) c5 =
    catala_malloc(sizeof(catala_array));
  const CATALA_OPTION(CATALA_ARRAY(CATALA_DEC)) c6;
  CATALA_ARRAY(CATALA_OPTION(CATALA_ARRAY(CATALA_DEC))) c7 =
    catala_malloc(sizeof(catala_array));
  const CATALA_OPTION(CATALA_ARRAY(CATALA_DEC)) c8;
  const CATALA_ARRAY(CATALA_DEC) c1;
  Baz* Baz = catala_malloc(sizeof(Baz));

  a = baz_in->a_in;
  code_and_env = a;
  a3->size = 1;
  a3->elements = catala_malloc(1 * sizeof(void*));
  a3->elements[0] =
    ((const CATALA_OPTION(Bar*)(*)(const CLOSURE_ENV, CATALA_UNIT))
     code_and_env->funcp)(code_and_env->env, CATALA_UNITVAL);
  a4 = handle_exceptions(pos, a3);┌─[ERROR]─
│
│  Unexpected error: key 'Eoption' not found in map
│
└─
#return code 125#
