/* This file has been generated by the Catala compiler, do not edit! */

#include <stdio.h>
#include <stdlib.h>
#include <runtime.c>


typedef struct Foo {
  CATALA_BOOL x;
  CATALA_DEC y;
} Foo;

typedef struct Baz {
  CATALA_DEC b;
  const CATALA_ARRAY(CATALA_DEC) c;
} Baz;

enum Bar_code {
  Bar_No,
  Bar_Yes
} Bar_code;

typedef struct Bar {
  enum Bar_code code;
  union {
    CATALA_UNIT No;
    const Foo* Yes;
  } payload;
} Bar;

typedef struct Baz_in {
  const catala_closure* a_in;
} Baz_in;

const Baz* baz (const Baz_in* baz_in)
{
  const catala_closure* a;
  const Bar* a__2;
  const CATALA_OPTION(Bar*) a__3;
  const catala_closure* code_and_env;
  const CATALA_OPTION(Bar*) a__4;
  const Bar* a__1;
  CATALA_DEC b__1;
  const CATALA_OPTION(CATALA_DEC) b__2;
  const CATALA_OPTION(CATALA_DEC) b__3;
  CATALA_BOOL b__4;
  CATALA_DEC b;
  const CATALA_ARRAY(CATALA_DEC) c__1;
  const CATALA_OPTION(CATALA_ARRAY(CATALA_DEC)) c__2 =
    catala_malloc(sizeof(catala_option));
  CATALA_ARRAY(CATALA_DEC) c__3 = catala_malloc(sizeof(catala_array));
  const CATALA_ARRAY(CATALA_DEC) c;
  Baz* Baz = catala_malloc(sizeof(Baz));
  a = baz_in->a_in;
  code_and_env = a;
  a__4 = ((const CATALA_OPTION(Bar*)(*)(const CLOSURE_ENV, CATALA_UNIT))
          code_and_env->funcp)(code_and_env->env, CATALA_UNITVAL);
  if (a__4->code == catala_option_some) {
    const Bar* x = a__4->payload;
    a__3 = catala_some(x);
  } else {
    const Bar* a__5;
    const CATALA_OPTION(Bar*) a__6 = catala_malloc(sizeof(catala_option));
    Bar* a__7 = catala_malloc(sizeof(Bar));
    a__7->code = Bar_No;
    a__7->payload.No = CATALA_UNITVAL;
    a__6 = catala_some(a__7);
    if (a__6->code == catala_option_some) {
      const Bar* arg = a__6->payload;
      a__5 = arg;
    } else {
      static const catala_code_position pos[1] =
        {{"tests/backends/simple.catala_en", 11, 11, 11, 12}};
      catala_error(catala_no_value, pos);
    }
    a__3 = catala_some(a__5);
  }
  if (a__3->code == catala_option_some) {
    const Bar* arg = a__3->payload;
    a__2 = arg;
  } else {
    static const catala_code_position pos[1] =
      {{"tests/backends/simple.catala_en", 11, 11, 11, 12}};
    catala_error(catala_no_value, pos);
  }
  a__1 = a__2;
  switch (a__1->code) {
    case Bar_No: {
      b__4 = CATALA_TRUE;
      break;
    }
    case Bar_Yes: {
      b__4 = CATALA_FALSE;
      break;
    }
  }
  if (b__4 == CATALA_TRUE) {
    b__3 = catala_some(catala_new_dec_str("42"));
  } else {
    b__3 = CATALA_NONE;
  }
  if (b__3->code == catala_option_some) {
    CATALA_DEC x__1 = b__3->payload;
    b__2 = catala_some(x__1);
  } else {
    CATALA_DEC b__5;
    switch (a__1->code) {
      case Bar_No: {
        b__5 = catala_new_dec_str("0");
        break;
      }
      case Bar_Yes: {
        Foo* foo = a__1->payload.Yes;
        CATALA_DEC b__6;
        if (foo->x == CATALA_TRUE) {
          b__6 = catala_new_dec_str("1");
        } else {
          b__6 = catala_new_dec_str("0");
        }
        b__5 = o_add_rat_rat(foo->y, b__6);
        break;
      }
    }
    b__2 = catala_some(b__5);
  }
  if (b__2->code == catala_option_some) {
    CATALA_DEC arg__1 = b__2->payload;
    b__1 = arg__1;
  } else {
    static const catala_code_position pos[1] =
      {{"tests/backends/simple.catala_en", 12, 10, 12, 11}};
    catala_error(catala_no_value, pos);
  }
  b = b__1;
  c__3->size = 2;
  c__3->elements = catala_malloc(2 * sizeof(void*));
  c__3->elements[0] = b;
  c__3->elements[1] = b;
  c__2 = catala_some(c__3);
  if (c__2->code == catala_option_some) {
    const CATALA_ARRAY(CATALA_DEC) arg__2 = c__2->payload;
    c__1 = arg__2;
  } else {
    static const catala_code_position pos[1] =
      {{"tests/backends/simple.catala_en", 13, 10, 13, 11}};
    catala_error(catala_no_value, pos);
  }
  c = c__1;
  Baz->b = b;
  Baz->c = c;
  return Baz;
}

int main (int argc, char** argv)
{
  catala_init();
  return 0;
}
