/* This file has been generated by the Catala compiler, do not edit! */

#include <stdio.h>
#include <stdlib.h>
#include <runtime.c>


typedef struct Foo {
  CATALA_BOOL x;
  CATALA_DEC y;
} Foo;

typedef struct Baz {
  CATALA_DEC b;
  const CATALA_ARRAY(CATALA_DEC) c;
} Baz;

enum Bar_code {
  Bar_No,
  Bar_Yes
} Bar_code;

typedef struct Bar {
  enum Bar_code code;
  union {
    CATALA_UNIT No;
    const Foo* Yes;
  } payload;
} Bar;

typedef struct Baz_in {
  const catala_closure* a_in;
} Baz_in;

const Baz* baz (const Baz_in* baz_in)
{
  const catala_closure* a;
  const Bar* a__1;
  const CATALA_OPTION(Bar*) a__2;
  const catala_closure* code_and_env;
  const CATALA_OPTION(Bar*) a__3;
  CATALA_DEC b;
  const CATALA_OPTION(CATALA_DEC) b__1;
  const CATALA_OPTION(CATALA_DEC) b__2;
  CATALA_BOOL b__3;
  const CATALA_ARRAY(CATALA_DEC) c;
  const CATALA_OPTION(CATALA_ARRAY(CATALA_DEC)) c__1 =
    catala_malloc(sizeof(catala_option));
  CATALA_ARRAY(CATALA_DEC) c__2 = catala_malloc(sizeof(catala_array));
  Baz* baz__1 = catala_malloc(sizeof(Baz));
  a = baz_in->a_in;
  code_and_env = a;
  a__3 = ((const CATALA_OPTION(Bar*)(*)(const CLOSURE_ENV, CATALA_UNIT))
          code_and_env->funcp)(code_and_env->env, CATALA_UNITVAL);
  if (a__3->code == catala_option_some) {
    a__2 = catala_some(a__3->payload);
  } else {
    const Bar* a__4;
    const CATALA_OPTION(Bar*) a__5 = catala_malloc(sizeof(catala_option));
    Bar* a__6 = catala_malloc(sizeof(Bar));
    a__6->code = Bar_No;
    a__6->payload.No = CATALA_UNITVAL;
    a__5 = catala_some(a__6);
    if (a__5->code == catala_option_some) {
      a__4 = a__5->payload;
    } else {
      static const catala_code_position pos[1] =
        {{"tests/backends/simple.catala_en", 11, 11, 11, 12}};
      catala_error(catala_no_value, pos);
    }
    a__2 = catala_some(a__4);
  }
  if (a__2->code == catala_option_some) {
    a__1 = a__2->payload;
  } else {
    static const catala_code_position pos[1] =
      {{"tests/backends/simple.catala_en", 11, 11, 11, 12}};
    catala_error(catala_no_value, pos);
  }
  switch (a__1->code) {
    case Bar_No: {
      b__3 = CATALA_TRUE;
      break;
    }
    case Bar_Yes: {
      b__3 = CATALA_FALSE;
      break;
    }
  }
  if (b__3 == CATALA_TRUE) {
    b__2 = catala_some(catala_new_dec_str("42"));
  } else {
    b__2 = CATALA_NONE;
  }
  if (b__2->code == catala_option_some) {
    b__1 = catala_some(b__2->payload);
  } else {
    CATALA_DEC b__4;
    switch (a__1->code) {
      case Bar_No: {
        b__4 = catala_new_dec_str("0");
        break;
      }
      case Bar_Yes: {
        Foo* foo = a__1->payload.Yes;
        CATALA_DEC b__5;
        if (foo->x == CATALA_TRUE) {
          b__5 = catala_new_dec_str("1");
        } else {
          b__5 = catala_new_dec_str("0");
        }
        b__4 = o_add_rat_rat(foo->y, b__5);
        break;
      }
    }
    b__1 = catala_some(b__4);
  }
  if (b__1->code == catala_option_some) {
    b = b__1->payload;
  } else {
    static const catala_code_position pos[1] =
      {{"tests/backends/simple.catala_en", 12, 10, 12, 11}};
    catala_error(catala_no_value, pos);
  }
  c__2->size = 2;
  c__2->elements = catala_malloc(2 * sizeof(void*));
  c__2->elements[0] = b;
  c__2->elements[1] = b;
  c__1 = catala_some(c__2);
  if (c__1->code == catala_option_some) {
    c = c__1->payload;
  } else {
    static const catala_code_position pos[1] =
      {{"tests/backends/simple.catala_en", 13, 10, 13, 11}};
    catala_error(catala_no_value, pos);
  }
  baz__1->b = b;
  baz__1->c = c;
  return baz__1;
}

int main (int argc, char** argv)
{
  catala_init();
  return 0;
}
