(rule
 (targets language_j.ml language_j.mli)
 (deps language.atd)
 (action
  (run atdgen -j -j-std %{deps})))

(rule
 (targets language_t.ml language_t.mli)
 (deps language.atd)
 (action
  (run atdgen -t %{deps})))

(library
 (name atd_language)
 (public_name catala.atd-language)
 (modules language_j language_t)
 (wrapped false)
 (libraries catala_utils shared_ast atdgen-runtime)
)

(executable
 (name macro_lang_gen)
 (modules macro_lang_gen)
 (libraries catala_utils shared_ast sedlex atd_language))
