labels:
  backend: docker

when:
  - event: manual

steps:
  - name: build-image
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: registry.gitlab.inria.fr
      repo: registry.gitlab.inria.fr/catala/registry
      username:
        from_secret: inria-registry-login
      password:
        from_secret: inria-registry-pass
      cache_images:
        - registry.gitlab.inria.fr/catala/registry:cache
      tags: ${CI_PIPELINE_STARTED}
      target: dev-build-context

  - name: set-usage
    image: alpine:3.22
    commands:
      - sed -i "s#&catala_image .*#\&catala_image ${CI_REGISTRY}:${CI_PIPELINE_STARTED}#" .woodpecker.yaml

  - name: commit-usage
    image: appleboy/drone-git-push
    settings:
      branch: ${GIT_COMMIT_BRANCH}
      commit: true
      commit_message: "CI: update to new base image tag"
