labels:
  platform: windows/amd64
  backend: local

when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: manual
    evaluate: 'not("REBUILD_IMAGE" in $env)'

variables:
  - &env
    OPAMCONFIRMLEVEL: unsafe-yes
    OPAMERRLOGLEN: 0
    OPAMROOT: C:\Users\CI\woodpecker\opam
    OCAMLRUNPARAM: b
    DUNE_PROFILE: check
    DUNE_CACHE: disabled
    COLUMNS: "165"
    # Ensures the side-by-side diff isn't truncated to less than 80 cols
    CI: "true"
    # Otherwise 're' fails to build with dune errors

steps:

  # Already done on the host
  # - name: opam
  #   image: powershell
  #   commands:
  #     - winget install Git.Git OCaml.opam

  - name: ocaml
    image: powershell
    environment: *env
    commands:
      - mkdir $env:HOME/.opam # Workaround a bug in opam
      - opam switch create . --empty
      - opam install ./catala.opam --deps-only

  - name: install
    image: powershell
    environment: *env
    commands:
      - (& opam env) -split '\r?\n' | ForEach-Object { Invoke-Expression $$_ }
      - dune build --only-packages catala
      - opam install ./catala.opam --working-dir --assume-built

  - name: test
    image: powershell
    environment: *env
    commands:
      - (& opam env) -split '\r?\n' | ForEach-Object { Invoke-Expression $$_ }
      - dune exec -- clerk test tests doc
      - dune exec -- clerk test tests --backend ocaml -c--disable-warnings --vars CC=x86_64-w64-mingw32-gcc

  - name: examples
    image: powershell
    environment: *env
    commands:
      - (& opam env) -split '\r?\n' | ForEach-Object { Invoke-Expression $$_ }
      - git clone https://github.com/CatalaLang/catala-examples --depth 1
      - cd catala-examples
      - clerk test
