/* This file has been generated by the Catala compiler, do not edit! */

#ifndef __DATE_INTERNAL_H__
#define __DATE_INTERNAL_H__


CATALA_DATE DateInternal__of_ymd
    (CATALA_POSITION pos,
     CATALA_INT dyear,
     CATALA_INT dmonth,
     CATALA_INT dday);

const CATALA_TUPLE(CATALA_INT;CATALA_INT;CATALA_INT) DateInternal__to_ymd
    (CATALA_DATE d);

CATALA_DATE DateInternal__last_day_of_month (CATALA_DATE d);

#endif /* __DATE_INTERNAL_H__ */
