name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows-smoke:
    name: Windows build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install opam and Ninja via winget
        run: |
          winget install --id OCaml.opam --source winget --accept-package-agreements --accept-source-agreements --silent
          winget install --id Ninja-build.Ninja --source winget --accept-package-agreements --accept-source-agreements --silent

      - name: Refresh PATH from registry
        shell: pwsh
        run: |
          $machinePath = [System.Environment]::GetEnvironmentVariable("Path","Machine")
          $userPath = [System.Environment]::GetEnvironmentVariable("Path","User")
          "$machinePath;$userPath" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Initialize opam (non-interactive) and create switch
        run: |
          opam init -y --bare --disable-sandboxing
          opam switch create 5.3.0
          opam switch 5.3.0
          opam --version

      - name: Build and install Catala through opam
        run: |
          opam update
          opam install . -y

      - name: Run built-in tests
        run: |
          opam exec -- dune test

      - name: Clone catala-examples
        run: |
          $ErrorActionPreference = 'Stop'
          $dst = "$env:USERPROFILE\catala-examples"
          if (Test-Path $dst) { Remove-Item -Recurse -Force $dst }
          git clone https://github.com/CatalaLang/catala-examples --depth 1 -b master $dst

      - name: Run clerk test in catala-examples
        continue-on-error: true # This fails because of an incompatibility
                                # of Windows Ninja. FIXME
        run: |
          Push-Location "$env:USERPROFILE\catala-examples"
          opam exec -- clerk test
          Pop-Location
